package com.kirin.mt.core.network

object BiliApiEndpoints {
  const val ApiBase = "https://api.bilibili.com"
  const val PassportBase = "https://passport.bilibili.com"
  const val AppBase = "https://app.bilibili.com"

  const val WbiNav = "$ApiBase/x/web-interface/nav"
  const val BuvidSpi = "$ApiBase/x/frontend/finger/spi"
  const val BuvidActivate = "$ApiBase/x/internal/gaia-gateway/ExClimbWuzhi"
  const val Recommend = "$ApiBase/x/web-interface/wbi/index/top/feed/rcmd"
  const val Popular = "$ApiBase/x/web-interface/popular"
  const val RegionFeedRcmd = "$ApiBase/x/web-interface/region/feed/rcmd"
  const val RegionBanner = "$ApiBase/x/web-show/region/banner"
  const val View = "$ApiBase/x/web-interface/view"
  const val ArchiveRelated = "$ApiBase/x/web-interface/archive/related"
  const val ArchiveLike = "$ApiBase/x/web-archive/like"
  const val CoinAdd = "$ApiBase/x/web-interface/coin/add"
  const val FavoriteDeal = "$ApiBase/x/v3/fav/resource/deal"
  const val SpaceArcSearch = "$ApiBase/x/space/wbi/arc/search"
  const val SpaceAccInfo = "$ApiBase/x/space/acc/info"
  const val Relation = "$ApiBase/x/relation"
  const val RelationModify = "$ApiBase/x/relation/modify"
  const val RelationStat = "$ApiBase/x/relation/stat"
 const val DynamicFeed = "$ApiBase/x/polymer/web-dynamic/v1/feed/all"
 const val DynamicUnread = "$ApiBase/x/polymer/web-dynamic/v1/feed/unread"
 const val DynamicLike = "$ApiBase/x/polymer/web-dynamic/v1/like/like"
 const val ToviewAdd = "$ApiBase/x/v2/history/toview"
 const val HistoryCursor = "$ApiBase/x/web-interface/history/cursor"
 const val FavoriteFolderListAll = "$ApiBase/x/v3/fav/folder/created/list-all"
 const val FavoriteResourceList = "$ApiBase/x/v3/fav/resource/list"
 const val FollowingSeasonList = "$ApiBase/x/space/bangumi/follow/list"
 const val Search = "$ApiBase/x/web-interface/wbi/search/type"
  const val SearchSuggest = "https://s.search.bilibili.com/main/suggest"
  const val PlayUrl = "$ApiBase/x/player/wbi/playurl"
  const val PlayerVideoshot = "$ApiBase/x/player/videoshot"
  const val PlayerDanmaku = "$ApiBase/x/v1/dm/list.so"
  const val CommentBase = "https://comment.bilibili.com"
  const val CommentReply = "$ApiBase/x/v2/reply"
  const val SponsorBlockSkipSegments = "https://bsbsb.top/api/skipSegments"
  const val PlayerOnlineTotal = "$ApiBase/x/player/online/total"
  const val PlayerHeartbeat = "$ApiBase/x/click-interface/web/heartbeat"
  const val PgcFeedV3 = "$ApiBase/pgc/page/web/v3/feed"
  const val PgcFeed = "$ApiBase/pgc/page/web/feed"
  const val PgcSeasonView = "$ApiBase/pgc/view/web/season"
  const val PgcPlayUrl = "$ApiBase/pgc/player/web/playurl"
  const val PgcSeasonIndex = "$ApiBase/pgc/season/index/result"
  const val PgcHeartbeat = "$ApiBase/pgc/player/web/heartbeat"
  const val TvQrCode = "$PassportBase/x/passport-tv-login/qrcode/auth_code"
  const val TvQrPoll = "$PassportBase/x/passport-tv-login/qrcode/poll"

  fun legacyDanmaku(cid: Long): String = "$CommentBase/$cid.xml"
}
