package com.kirin.mt.core.player

import android.util.Log
import androidx.annotation.OptIn
import androidx.media3.common.C
import androidx.media3.common.Format
import androidx.media3.common.MediaItem
import androidx.media3.common.MimeTypes
import androidx.media3.common.Player
import androidx.media3.common.util.UnstableApi
import androidx.media3.datasource.DataSource
import androidx.media3.exoplayer.source.MediaSource
import androidx.media3.exoplayer.source.MergingMediaSource
import androidx.media3.exoplayer.source.ProgressiveMediaSource
import androidx.media3.exoplayer.source.SubtitleLazyLoadingSupport
import androidx.media3.extractor.ExtractorsFactory
import androidx.media3.extractor.text.DefaultSubtitleParserFactory
import androidx.media3.extractor.text.SubtitleExtractor
import java.util.concurrent.TimeUnit
import okhttp3.OkHttpClient

/**
 * P11-120:YouTube 字幕接入(player 侧公共件,TV 与移动端共用)。
 *
 * ## 背景:P11-73 为什么下线,这次为什么能回来
 *
 * P11-72 真机:视频转圈加载不出、官方可播。根因是**旧实现把每条 WebVTT 字幕轨都做成一个普通
 * ProgressiveMediaSource 并进 MergingMediaSource** —— media3 要**全部** child prepare 完才
 * selectTracks,而 `SubtitleExtractor` 要读完整个文件才声明轨,于是 timedtext 响应头被掐时字幕
 * period 永久挂死,把主源一起拖死(日志:零条 `fetch rn=` + `ProgressiveMediaPeriod` +
 * `Http2Stream.takeHeaders` 81s)。当时的结论是「字幕 URL 对播放不可信」,整块移除。
 *
 * 现在的做法把「不可信」这件事结构性解决掉,四道防线:
 *  ① **懒加载**([SubtitleLazyLoadingSupport])——prepare 期零读取,未选中不发请求;
 *  ② **独立短超时 DataSource**([createShortTimeoutClient])——真断了 5s 内失败,不占 loader 太久;
 *  ③ **失败即弃**——懒加载开不起来就整条字幕轨不挂(宁可不显示字幕,也不给主源留任何阻塞机会);
 *  ④ **默认关闭**——只有用户显式选语言才 enable TEXT 轨,默认零字幕流量。
 *
 * 另:2026-09-17 复测,timedtext 真实签名 URL 直连可用(200 / 0.6~1.8s / 真 WEBVTT,不需要
 * poToken;无签名 URL 才是空 200),即 P11-72 当时是**偶发黑洞**而非结构性封禁。
 */
@OptIn(UnstableApi::class)
object SubtitleTracks {

  /**
   * 字幕专用短超时 client:与播放主源共享连接池/dispatcher(只覆盖超时),不另建连接池。
   *
   * 主源 client(`createPlaybackClient`)是 `callTimeout=0` + 15s 读超时(为流式拉流故意放宽),
   * 对字幕这种「一次性小文件、失败无所谓」的请求太宽松——黑洞时要挂 15s。这里压到 5s/8s:
   * 通了就通(实测 0.6~1.8s),不通就快速失败,字幕不显示而已。
   */
  fun createShortTimeoutClient(base: OkHttpClient): OkHttpClient {
    return base.newBuilder()
      .connectTimeout(SubtitleConnectTimeoutSeconds, TimeUnit.SECONDS)
      .readTimeout(SubtitleReadTimeoutSeconds, TimeUnit.SECONDS)
      .writeTimeout(SubtitleReadTimeoutSeconds, TimeUnit.SECONDS)
      .callTimeout(SubtitleCallTimeoutSeconds, TimeUnit.SECONDS)
      .build()
  }

  /**
   * 把字幕轨挂到主源上:每条字幕一个**懒加载**的 ProgressiveMediaSource,再 MergingMediaSource 合并。
   *
   * 无可用字幕轨(空列表 / 懒加载开启失败)时原样返回 [mainSource](不合并、零副作用)。
   */
  fun attach(
    mainSource: MediaSource,
    dataSourceFactory: DataSource.Factory,
    subtitleTracks: List<PlaybackTrack>,
  ): MediaSource {
    if (subtitleTracks.isEmpty()) return mainSource
    val sources = subtitleTracks.mapNotNull { track ->
      createLazySource(dataSourceFactory, track) ?: run {
        // 具体原因由 createLazySource 内部日志给出(URL 空 / 无解析器 / 懒加载未开启 / 构造抛错)。
        // 这里统一丢弃:没有懒加载保障的字幕轨宁可不挂,也不给主源留阻塞机会。
        Log.w(LogTag, "字幕轨已跳过 id=${track.id} lang=${track.languageCode}")
        null
      }
    }
    if (sources.isEmpty()) return mainSource
    Log.i(LogTag, "字幕已挂载: ${sources.size}/${subtitleTracks.size} 轨(懒加载,未选中不读数据)")
    // 每轨实际要拉的 URL 的 fmt —— 格式不对(如拿到 TTML/XML 却按 text/vtt 解析)会让媒体3 抛
    // "Expected WEBVTT" 并静默 disable 该轨(P11-120 真机就是这么翻车的),故把判据直接写进日志。
    subtitleTracks.forEach { track ->
      Log.i(LogTag, "字幕轨 id=${track.id} lang=${track.languageCode} asr=${track.isAutoGenerated} fmt=${fmtOf(track.baseUrl)} name=${track.displayName}")
    }
    return MergingMediaSource(mainSource, *sources.toTypedArray())
  }

  /**
   * 单条字幕轨 → 懒加载 ProgressiveMediaSource。任何一步不成(URL 空 / 解析器不支持 / 懒加载开关
   * 没打开 / 构造抛错)都返回 null,**调用方须丢弃该轨** —— 字幕绝不能给主源留下 fail 或阻塞的机会。
   */
  fun createLazySource(dataSourceFactory: DataSource.Factory, track: PlaybackTrack): MediaSource? {
    if (track.baseUrl.isEmpty()) return null
    return runCatching { buildLazySource(dataSourceFactory, track) }
      .onFailure { Log.w(LogTag, "字幕轨构造失败,已跳过 id=${track.id}: ${it.javaClass.simpleName}: ${it.message}") }
      .getOrNull()
  }

  private fun buildLazySource(dataSourceFactory: DataSource.Factory, track: PlaybackTrack): MediaSource? {
    val parserFactory = DefaultSubtitleParserFactory()
    val subtitleFormat = Format.Builder()
      .setId(track.id.toString())
      .setSampleMimeType(MimeTypes.TEXT_VTT)
      .setLanguage(track.languageCode)
      .setLabel(track.displayName)
      .setRoleFlags(if (track.isAutoGenerated) C.ROLE_FLAG_SUPPLEMENTARY else C.ROLE_FLAG_CAPTION)
      .build()
    if (!parserFactory.supportsFormat(subtitleFormat)) {
      Log.w(LogTag, "无 text/vtt 解析器,已跳过 id=${track.id}")
      return null
    }
    // 注意第二个参数传 **null**:懒加载路径下轨已由 ProgressiveMediaPeriod 依 singleTrackFormat
    // 声明(见 ProgressiveMediaPeriod.prepare 的 singleTrackFormat 分支),SubtitleExtractor 若再持
    // format 就会重复调用 TrackOutput.format/endTracks/seekMap。media3 自己的
    // DefaultMediaSourceFactory 处理 SubtitleConfiguration 时同样传 null。
    val extractorsFactory = ExtractorsFactory {
      arrayOf(SubtitleExtractor(parserFactory.create(subtitleFormat), null))
    }
    val factory = ProgressiveMediaSource.Factory(dataSourceFactory, extractorsFactory)
      .setLoadOnlySelectedTracks(true)
    // 传给懒加载的是**转码后**的 format(cues 轨):SubtitleExtractor 输出的就是 cues,
    // 与 media3 DefaultMediaSourceFactory 的构造逐字段一致。
    val cuesFormat = subtitleFormat.buildUpon()
      .setSampleMimeType(MimeTypes.APPLICATION_MEDIA3_CUES)
      .setCodecs(subtitleFormat.sampleMimeType)
      .setCueReplacementBehavior(parserFactory.getCueReplacementBehavior(subtitleFormat))
      .build()
    if (!SubtitleLazyLoadingSupport.enable(factory, SubtitleExtractor.TRACK_ID, cuesFormat)) return null
    return factory.createMediaSource(MediaItem.fromUri(track.baseUrl))
  }

  /**
   * 应用字幕选择:[trackId]=null 表示关闭(禁用 TEXT 轨),否则按语言 + role flags 精确选中该轨。
   *
   * 只动 track selection,不重建 MediaSource、不重解析会话——比切音轨(P11-119 要重开 SABR 会话)轻一个量级。
   * 关闭时用 `setTrackTypeDisabled` 而不是「不设偏好」,是为了压掉 media3 默认可能从系统
   * CaptioningManager 读到偏好而自动选轨(那会在起播时就去拉字幕 URL,违背防线 ④)。
   */
  fun applySelection(player: Player, subtitleTracks: List<PlaybackTrack>, trackId: Int?) {
    if (subtitleTracks.isEmpty()) return
    val track = trackId?.let { id -> subtitleTracks.firstOrNull { it.id == id } }
    val builder = player.trackSelectionParameters.buildUpon()
      .setTrackTypeDisabled(C.TRACK_TYPE_TEXT, track == null)
    if (track != null) {
      builder
        .setPreferredTextLanguage(track.languageCode)
        .setPreferredTextRoleFlags(if (track.isAutoGenerated) C.ROLE_FLAG_SUPPLEMENTARY else C.ROLE_FLAG_CAPTION)
      Log.i(LogTag, "字幕已选: id=${track.id} lang=${track.languageCode} asr=${track.isAutoGenerated}")
    } else {
      Log.i(LogTag, "字幕已关闭")
    }
    player.setTrackSelectionParameters(builder.build())
  }

  /** 从字幕 URL 里取 `fmt` 参数值(诊断日志用;无则 "?"),不打印完整签名 URL。 */
  private fun fmtOf(url: String): String {
    val query = url.substringAfter('?', "")
    return query.split("&").firstOrNull { it.startsWith("fmt=") }?.substringAfter('=') ?: "?"
  }

  /** 字幕轨显示名(面板/设置项用)。自动生成轨由 UI 追加本地化后缀([PlaybackTrack.isAutoGenerated])。 */
  fun labelOf(track: PlaybackTrack): String {
    return track.displayName?.takeIf { it.isNotBlank() }
      ?: track.languageCode?.takeIf { it.isNotBlank() }
      ?: track.id.toString()
  }

  private const val SubtitleConnectTimeoutSeconds = 5L
  private const val SubtitleReadTimeoutSeconds = 5L
  private const val SubtitleCallTimeoutSeconds = 8L
}

private const val LogTag = "BiliSubtitle"
